# Generated by Django 6.1 on 2026-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Negocio', max_length=120)),
                ('rif', models.CharField(max_length=20, verbose_name='RIF')),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('serial_impresora_fiscal', models.CharField(blank=True, help_text='Se usa como número de control en la factura', max_length=60, verbose_name='Serial de impresora fiscal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('notas_factura', models.TextField(blank=True, help_text='Ej: Gracias por su compra · Conserve este documento', verbose_name='Notas al pie de la factura')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activada', models.BooleanField(default=False)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('dias_licencia', models.PositiveIntegerField(default=365)),
            ],
            options={
                'verbose_name': 'Licencia',
            },
        ),
    ]
