# Generated by Django 6.1 on 2026-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impresorafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignegocio',
            name='tasa_dolar',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Actualiza a diario. Todos los precios se venden en Bs = $ x tasa.', max_digits=12, verbose_name='Tasa del dólar (Bs por $)'),
        ),
    ]
