# Generated by Django 6.1 on 2026-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modo_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignegocio',
            name='serial_impresora_fiscal',
            field=models.CharField(blank=True, help_text='Ej: FXD12F o Z1F0012065. En modo fiscal ES el N° de control.', max_length=60, verbose_name='Número de caja / serial fiscal'),
        ),
    ]
