# Generated by Django 6.1 on 2026-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ajustes_confignegocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresorafiscal',
            name='baud',
            field=models.PositiveIntegerField(default=9600),
        ),
        migrations.AddField(
            model_name='impresorafiscal',
            name='conexion',
            field=models.CharField(choices=[('txt', 'Descargar .txt'), ('serial', 'Serial (COM)'), ('red', 'Red (IP:puerto)'), ('compartida', 'Compartida Windows/Linux')], default='txt', max_length=12),
        ),
        migrations.AddField(
            model_name='impresorafiscal',
            name='ip',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='impresorafiscal',
            name='nombre_compartido',
            field=models.CharField(blank=True, help_text='Ej: \\\\PC\\EPSON (Windows) o nombre lp (Linux)', max_length=80),
        ),
        migrations.AddField(
            model_name='impresorafiscal',
            name='puerto_red',
            field=models.PositiveIntegerField(default=9100),
        ),
        migrations.AddField(
            model_name='impresorafiscal',
            name='puerto_serial',
            field=models.CharField(blank=True, default='COM1', max_length=20),
        ),
    ]
