# Generated by Django 6.1 on 2026-08-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cambio_venta_monto_recibido_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
