# Generated by Django 6.1 on 2026-08-12 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='destino_diferencia',
            field=models.CharField(blank=True, choices=[('cajero', 'Asumida por el cajero'), ('cliente', 'Devuelta al cliente'), ('ingreso', 'Ingreso extraordinario')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_regularizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='nota_regularizacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='regularizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caja',
            name='regularizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_regularizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
