# Generated by Django 6.1 on 2026-08-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0004_caja_destino_diferencia_caja_fecha_regularizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='cliente_reclamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_caja', to='clientes.cliente'),
        ),
    ]
