# Generated by Django 6.1 on 2026-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_caja_cliente_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='historial_regularizacion',
            field=models.TextField(blank=True),
        ),
    ]
