# Generated by Django 6.1 on 2026-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_caja_historial_regularizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
