# Generated by Django 6.1 on 2026-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_base_imponible_venta_monto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('punto_venta', 'Punto de venta'), ('bio_pago', 'Bio Pago')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('punto_venta', 'Punto de venta'), ('bio_pago', 'Bio Pago'), ('credito', 'Crédito (fiado)'), ('mixto', 'Mixto')], default='efectivo', max_length=15),
        ),
    ]
