# Generated by Django 6.1 on 2026-08-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impresorafiscal'),
        ('ventas', '0008_alter_pago_metodo_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.impresorafiscal'),
        ),
    ]
