# Generated by Django 6.1 on 2026-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_caja_impresora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='serial_fiscal',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
