# Generated by Django 6.1 on 2026-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='impresa',
            field=models.BooleanField(default=False, verbose_name='Impresa'),
        ),
    ]
