# Generated by Django 6.1 on 2026-08-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_impresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('caja_procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_procesadas', to='ventas.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_creadas', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.detalleventa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacredito')),
            ],
        ),
    ]
