# Generated by Django 6.1 on 2026-08-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_notacredito_notacreditodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(help_text='Número secuencial de control fiscal', max_length=20, verbose_name='N° de Control')),
                ('numero_factura', models.CharField(max_length=20, verbose_name='N° de Factura')),
                ('fecha_factura', models.DateField(verbose_name='Fecha factura')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_rif', models.CharField(blank=True, max_length=30, verbose_name='RIF/CI')),
                ('total_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Exento')),
                ('base_imponible_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base imponible IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto IVA')),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Alícuota IVA %')),
                ('iva_retenido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='IVA retenido')),
                ('numero_comprobante', models.CharField(blank=True, max_length=20, verbose_name='N° comprobante retención')),
                ('notas_credito_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total notas de crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='libro_venta', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Libro de Venta',
                'verbose_name_plural': 'Libro de Ventas',
                'ordering': ['-fecha_factura', '-numero_factura'],
            },
        ),
    ]
