# Generated by Django 6.1 on 2026-08-28 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_idx_cli_nombres_cliente_idx_cli_ci'),
        ('ventas', '0015_venta_numero_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='idx_venta_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='idx_venta_estado'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'fecha'], name='idx_venta_usr_fec'),
        ),
    ]
