# Generated by Django 6.1 on 2026-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_venta_idx_venta_fecha_venta_idx_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hash_factura',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash de integridad'),
        ),
        migrations.AddField(
            model_name='venta',
            name='hash_prev',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash anterior'),
        ),
    ]
