# Generated by Django 6.1 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_hash_chain_facturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodetalle',
            name='referencia',
            field=models.CharField(blank=True, help_text='N° de operación, Zelle, etc.', max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='N° de operación, Zelle, etc.', max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Bs)'), ('efectivo_usd', 'Efectivo ($)'), ('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia'), ('zelle', 'Zelle'), ('punto_venta', 'Punto de venta'), ('bio_pago', 'Bio Pago'), ('credito', 'Crédito (Fiado)')], max_length=15),
        ),
    ]
