# Generated by Django 6.1 on 2026-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='grava_iva',
            field=models.BooleanField(default=False, verbose_name='Paga IVA (16%)'),
        ),
    ]
