# Generated by Django 6.1 on 2026-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_grava_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='por_peso',
            field=models.BooleanField(default=False, verbose_name='Se vende por peso (granel)'),
        ),
    ]
