# Generated by Django 6.1 on 2026-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_por_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra'), ('l', 'Litro'), ('ml', 'Mililitro'), ('docena', 'Docena'), ('paquete', 'Paquete'), ('m', 'Metro')], default='unidad', max_length=10),
        ),
    ]
