# Generated by Django 6.1 on 2026-08-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_unidad'),
        ('ventas', '0014_libroventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra/Entrada'), ('ajuste_pos', 'Ajuste +'), ('ajuste_neg', 'Ajuste -'), ('conteo', 'Conteo fisico'), ('inicial', 'Stock inicial')], max_length=12)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.venta')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
