# Generated by Django 6.1 on 2026-08-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombres'], name='idx_cli_nombres'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ci_nit'], name='idx_cli_ci'),
        ),
    ]
